// Todos los textos del bot (rioplatense, cortos)
export const T = {
  hello: 'Hola Diego 👋 ¿Qué querés cargar?',
  helloHint: 'También podés mandarme directo "1500 super galicia" o la foto de un ticket 🧾.',
  typeBtn: { expense: '💸 Gasto', income: '💰 Ingreso', transfer: '🔁 Transferencia' },
  askAmount: '¿Cuánto fue? (ej: 1500 o 1.500,50 · "20 usd" si es en dólares)',
  badAmount: 'No entendí el importe. Probá con un número, ej: 2500 o 1.250,50',
  askAccount: '¿Con qué cuenta?',
  askFrom: '¿Desde qué cuenta?',
  askTo: '¿Hacia qué cuenta?',
  askPayMonth: 'Es tarjeta 💳 ¿En qué resumen lo pagás?',
  payThis: (m) => `Este mes (${m})`,
  payNext: (m) => `Mes que viene (${m})`,
  payOther: 'Otro mes',
  askPayMonthText: 'Escribí el mes como 2026-12 o solo el número de mes (ej: 12)',
  badMonth: 'No entendí el mes. Escribilo como 2026-12.',
  askInst: '¿En cuántas cuotas?',
  badInst: 'Decime un número de cuotas entre 1 y 36.',
  askCategory: '¿Categoría?',
  askSub: '¿Subcategoría?',
  noSub: '— Sin subcategoría —',
  askNote: '¿Alguna nota? (o mandá "no")',
  askDate: '¿Fecha?',
  dateToday: 'Hoy', dateYesterday: 'Ayer', dateOther: 'Otra',
  askDateText: 'Escribí la fecha como dd/mm (ej: 7/10) o dd/mm/aaaa',
  badDate: 'No entendí la fecha. Probá dd/mm, ej: 7/10',
  confirmQ: '¿Lo guardo?',
  save: '✅ Guardar', change: '✏️ Cambiar', cancel: '❌ Cancelar',
  saved: 'Guardado ✅ Lo vas a ver en la app como pendiente de WhatsApp para confirmarlo.',
  saveFail: 'No pude guardarlo en la nube 😕 Probá de nuevo en un rato (seguimos con el mismo movimiento).',
  cancelled: 'Listo, cancelé el movimiento.',
  nothingToCancel: 'No había nada en curso. Mandame un importe o "hola" para empezar.',
  changeWhat: '¿Qué querés cambiar?',
  fields: { type: 'Tipo', amount: 'Importe', account: 'Cuenta', from: 'Desde', to: 'Hacia', category: 'Categoría', sub: 'Subcategoría', note: 'Nota', date: 'Fecha', dueMonth: 'Mes de pago', inst: 'Cuotas' },
  unknown: 'No te entendí 🤔 Respondé con una opción o escribí *cancelar*.',
  pickNumber: 'Respondé con el número de la opción (o escribí el nombre).',
  help: 'Podés:\n• Mandar un importe: "1500" o "1500 super galicia"\n• Mandar la foto de un ticket 🧾\n• Escribir "hola" para el menú\n• "cancelar" en cualquier momento\n• "actualizar" si cambiaste cuentas o categorías en la app',
  refreshed: 'Listo, actualicé cuentas y categorías desde la app ✅',
  readingTicket: 'Dale, leo el ticket… 🧾',
  ticketNoAi: 'No tengo IA configurada acá. Decime el total y lo cargo igual, o compartí la foto a la app (Compartir → Mis Finanzas).',
  ticketFail: 'No pude leer el ticket 😕 Decime el total y lo cargo igual.',
  ticketSummary: (r) => {
    const top = (r.items || []).filter((i) => !i.discount).slice(0, 4).map((i) => `${i.desc}${i.qty > 1 ? ' x' + i.qty : ''}`).join(', ');
    return `🧾 ${r.merchant || 'Ticket'} · ${r.date ? r.date.split('-').reverse().slice(0, 2).join('/') : ''} · Total ${r.totalTxt} · ${(r.items || []).length} ítems${top ? '\n' + top + (r.items.length > 4 ? '…' : '') : ''}${r.warnings && r.warnings.length ? '\n⚠️ ' + r.warnings[0] : ''}`;
  },
  askTicketAccount: '¿Con qué pagaste?',
  mediaMidFlow: 'Primero terminemos este movimiento (o mandá *cancelar*).',
  mediaTooBig: 'Mandámela como foto (no como archivo) así es más liviana.',
  understood: (s) => `Entendí: ${s}`,
  missing: (list) => `Me falta: ${list.join(', ')}.`,
  menuNumbered: (rows) => rows.map((r, i) => `${i + 1}) ${r.title}`).join('\n'),
};
